"""
Word Document Export Module

Generates Word documents (.docx) from research reports using python-docx.
"""

import io
import logging
import re
from datetime import datetime
from typing import List, Dict, Any, Optional
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE

logger = logging.getLogger(__name__)


async def export_to_word(
    report: str,
    query: str,
    sources: List[Dict[str, Any]],
    metadata: Optional[Dict[str, Any]] = None,
) -> bytes:
    """
    Export research report to Word document format.

    Args:
        report: The final research report in markdown format
        query: Original research query
        sources: List of sources used
        metadata: Additional metadata (session_id, timestamps, costs, etc.)

    Returns:
        Word document as bytes

    Raises:
        Exception: If Word document generation fails
    """
    try:
        # Create document
        doc = Document()

        # Set document properties
        _set_document_properties(doc, query, metadata)

        # Add custom styles
        _add_custom_styles(doc)

        # Title page
        _create_title_page(doc, query, metadata)
        doc.add_page_break()

        # Table of contents placeholder
        _create_toc_placeholder(doc)
        doc.add_page_break()

        # Main content
        _convert_markdown_to_word(doc, report)
        doc.add_page_break()

        # Sources
        if sources:
            _create_sources_section(doc, sources)

        # Save to buffer
        buffer = io.BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        docx_bytes = buffer.getvalue()
        buffer.close()

        logger.info(f"Generated Word document: {len(docx_bytes)} bytes")
        return docx_bytes

    except Exception as e:
        logger.error(f"Word document generation failed: {e}", exc_info=True)
        raise


def _set_document_properties(
    doc: Document, query: str, metadata: Optional[Dict[str, Any]]
):
    """
    Set document metadata properties.

    Args:
        doc: Document object
        query: Research query
        metadata: Additional metadata
    """
    core_properties = doc.core_properties
    core_properties.title = "Research Report"
    core_properties.subject = query
    core_properties.author = "Agentic Research AI"
    core_properties.comments = "Generated by Agentic AI Research System"

    if metadata and metadata.get("session_id"):
        core_properties.identifier = metadata["session_id"]


def _add_custom_styles(doc: Document):
    """
    Add custom paragraph and character styles to document.

    Args:
        doc: Document object
    """
    styles = doc.styles

    # Custom Title style
    if "CustomTitle" not in [s.name for s in styles]:
        title_style = styles.add_style("CustomTitle", WD_STYLE_TYPE.PARAGRAPH)
        title_style.font.size = Pt(24)
        title_style.font.bold = True
        title_style.font.color.rgb = RGBColor(31, 41, 55)
        title_style.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title_style.paragraph_format.space_after = Pt(30)

    # Custom Heading 2
    if "CustomHeading2" not in [s.name for s in styles]:
        h2_style = styles.add_style("CustomHeading2", WD_STYLE_TYPE.PARAGRAPH)
        h2_style.font.size = Pt(16)
        h2_style.font.bold = True
        h2_style.font.color.rgb = RGBColor(31, 41, 55)
        h2_style.paragraph_format.space_before = Pt(16)
        h2_style.paragraph_format.space_after = Pt(12)

    # Custom Heading 3
    if "CustomHeading3" not in [s.name for s in styles]:
        h3_style = styles.add_style("CustomHeading3", WD_STYLE_TYPE.PARAGRAPH)
        h3_style.font.size = Pt(14)
        h3_style.font.bold = True
        h3_style.font.color.rgb = RGBColor(55, 65, 81)
        h3_style.paragraph_format.space_before = Pt(12)
        h3_style.paragraph_format.space_after = Pt(8)

    # Code style
    if "CodeBlock" not in [s.name for s in styles]:
        code_style = styles.add_style("CodeBlock", WD_STYLE_TYPE.PARAGRAPH)
        code_style.font.name = "Courier New"
        code_style.font.size = Pt(9)
        code_style.paragraph_format.left_indent = Inches(0.5)
        code_style.paragraph_format.space_after = Pt(10)


def _create_title_page(doc: Document, query: str, metadata: Optional[Dict[str, Any]]):
    """
    Create title page.

    Args:
        doc: Document object
        query: Research query
        metadata: Metadata dictionary
    """
    # Add title
    title = doc.add_paragraph("Research Report", style="CustomTitle")

    # Add some space
    doc.add_paragraph()

    # Add query
    query_heading = doc.add_paragraph()
    query_heading.add_run("Research Query:").bold = True
    doc.add_paragraph(query)

    # Add metadata
    if metadata:
        doc.add_paragraph()

        table = doc.add_table(rows=0, cols=2)
        table.style = "Light Grid Accent 1"

        def add_metadata_row(label: str, value: str):
            row = table.add_row()
            row.cells[0].text = label
            row.cells[1].text = value
            row.cells[0].paragraphs[0].runs[0].bold = True

        if metadata.get("session_id"):
            add_metadata_row("Session ID:", metadata["session_id"])

        if metadata.get("created_at"):
            created_at = metadata["created_at"]
            if isinstance(created_at, datetime):
                created_at = created_at.strftime("%Y-%m-%d %H:%M:%S")
            add_metadata_row("Generated:", str(created_at))

        if metadata.get("duration"):
            duration = metadata["duration"]
            if duration:
                minutes = int(duration // 60)
                seconds = int(duration % 60)
                add_metadata_row("Duration:", f"{minutes}m {seconds}s")

        if metadata.get("cost"):
            cost = metadata["cost"]
            if cost:
                add_metadata_row("Cost:", f"${cost:.4f} USD")


def _create_toc_placeholder(doc: Document):
    """
    Create table of contents placeholder.

    Args:
        doc: Document object
    """
    doc.add_paragraph("Table of Contents", style="CustomHeading2")
    toc_para = doc.add_paragraph()
    toc_para.add_run(
        "1. Executive Summary\n"
        "2. Key Findings\n"
        "3. Detailed Analysis\n"
        "4. Sources & References"
    )


def _convert_markdown_to_word(doc: Document, markdown_text: str):
    """
    Convert markdown text to Word document elements.

    Handles:
    - Headers (# ## ###)
    - Bold (**text**)
    - Italic (*text*)
    - Code blocks (```code```)
    - Bullet points (- item)
    - Numbered lists (1. item)
    - Links ([text](url))

    Args:
        doc: Document object
        markdown_text: Markdown formatted text
    """
    lines = markdown_text.split("\n")
    i = 0
    in_code_block = False
    code_lines = []

    while i < len(lines):
        line = lines[i].strip()

        # Code block detection
        if line.startswith("```"):
            if in_code_block:
                # End code block
                code_text = "\n".join(code_lines)
                doc.add_paragraph(code_text, style="CodeBlock")
                code_lines = []
                in_code_block = False
            else:
                # Start code block
                in_code_block = True
            i += 1
            continue

        if in_code_block:
            code_lines.append(line)
            i += 1
            continue

        # Skip empty lines
        if not line:
            i += 1
            continue

        # Headers
        if line.startswith("### "):
            text = line[4:]
            doc.add_paragraph(text, style="CustomHeading3")
        elif line.startswith("## "):
            text = line[3:]
            doc.add_paragraph(text, style="CustomHeading2")
        elif line.startswith("# "):
            text = line[2:]
            doc.add_paragraph(text, style="CustomTitle")
        # Bullet points
        elif line.startswith("- ") or line.startswith("* "):
            text = line[2:]
            paragraph = doc.add_paragraph(style="List Bullet")
            _add_formatted_text(paragraph, text)
        # Numbered lists
        elif re.match(r"^\d+\.\s", line):
            text = re.sub(r"^\d+\.\s", "", line)
            paragraph = doc.add_paragraph(style="List Number")
            _add_formatted_text(paragraph, text)
        # Regular paragraph
        else:
            if line:
                paragraph = doc.add_paragraph()
                _add_formatted_text(paragraph, line)

        i += 1


def _add_formatted_text(paragraph, text: str):
    """
    Add formatted text to paragraph, handling markdown formatting.

    Args:
        paragraph: Paragraph object
        text: Text with markdown formatting
    """
    # Pattern to find bold, italic, code, and links
    pattern = r"(\*\*.*?\*\*|\*.*?\*|`.*?`|\[.*?\]\(.*?\))"

    parts = re.split(pattern, text)

    for part in parts:
        if not part:
            continue

        # Bold
        if part.startswith("**") and part.endswith("**"):
            run = paragraph.add_run(part[2:-2])
            run.bold = True
        # Italic
        elif part.startswith("*") and part.endswith("*") and not part.startswith("**"):
            run = paragraph.add_run(part[1:-1])
            run.italic = True
        # Inline code
        elif part.startswith("`") and part.endswith("`"):
            run = paragraph.add_run(part[1:-1])
            run.font.name = "Courier New"
            run.font.size = Pt(10)
        # Links
        elif part.startswith("[") and "](" in part:
            match = re.match(r"\[(.*?)\]\((.*?)\)", part)
            if match:
                link_text = match.group(1)
                url = match.group(2)
                run = paragraph.add_run(f"{link_text} ({url})")
                run.font.color.rgb = RGBColor(0, 0, 255)
                run.font.underline = True
        # Regular text
        else:
            paragraph.add_run(part)


def _create_sources_section(doc: Document, sources: List[Dict[str, Any]]):
    """
    Create sources and references section.

    Args:
        doc: Document object
        sources: List of source dictionaries
    """
    doc.add_paragraph("Sources & References", style="CustomHeading2")

    for idx, source in enumerate(sources, 1):
        # Create paragraph for each source
        para = doc.add_paragraph()

        # Add source number
        run = para.add_run(f"[{idx}] ")
        run.bold = True

        # Add title
        if source.get("title"):
            para.add_run(source["title"])
            para.add_run("\n")

        # Add URL
        if source.get("url"):
            run = para.add_run(source["url"])
            run.font.color.rgb = RGBColor(0, 0, 255)
            run.font.underline = True
            para.add_run("\n")

        # Add author
        if source.get("author"):
            para.add_run(f"Author: {source['author']}\n")

        # Add date
        if source.get("date"):
            para.add_run(f"Date: {source['date']}\n")

        # Add space between sources
        doc.add_paragraph()
